-- CareerBridge schema is created by backend/src/db.ts for SQLite.
-- Tables: users, sessions, candidate_profiles, organizations, jobs, saved_jobs,
-- applications, passid_sessions, passid_connections, passid_webhook_events,
-- verification_results, pay_payment_intents, pay_payment_events, audit_logs.
